usr/share/applications/org.kramden.spec.desktop
usr/share/applications/org.kramden.provision-secureerase.desktop
usr/bin/kramden-spec
usr/bin/kramden-provision-secureerase
etc/xdg/autostart/org.kramden.spec.desktop
usr/share/kramden-provision/scripts/bios_password.sh
usr/share/kramden-provision/scripts/dell.sh
usr/share/kramden-provision/scripts/asset.sh
usr/share/kramden-provision/scripts/clock.sh
usr/share/kramden-provision/scripts/kramden-secure-erase
usr/share/kramden-provision/scripts/kramden-reset-spec
usr/share/pixmaps/kramden_tracking_header.png
kramden-wallpaper.png usr/share/backgrounds/
99_kramden-spec.gschema.override usr/share/glib-2.0/schemas/
