#!/bin/bash
#

if [ "$USER" = "finaltest" ];
then
  # Delete the Kramden Deploy wifi connection
  nmcli c delete kramden-deploy 2/dev/null || true

  # Add connection for Kramden Guest network
  nmcli device wifi connect "Kramden Guest" password iamatkramden name kramden-guest 2/dev/null || true

  # delete finaltest user and homedir
  sudo userdel -rf finaltest
  # poweroff
  poweroff
fi
