#!/bin/bash
#

if [ "$USER" = "finaltest" ];
then
  # Delete the Kramden Deploy wifi connection
  nmcli c delete kramden-deploy 2/dev/null || true

  # Add connection for Kramden Guest network
  nmcli device wifi connect "Kramden Guest" password iamatkramden name kramden-guest 2/dev/null || true

  # delete finaltest user and homedir
  sudo userdel -rf finaltest

  # ensure we delete extra env set for sortly access
  sudo rm -f /etc/environment.d/99-kramden

  # eject CD/DVD drive to ensure empty
  eject

  # poweroff
  poweroff
fi
