#!/bin/bash
#
if [ "$USER" = "osload" ];
then
  # delete rc.local as it was only needed for provisioning
  sudo rm -f /etc/rc.local
  # delete osload user and homedir
  sudo userdel -rf osload
  # poweroff
  sudo poweroff
fi
